// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2W9uDCKTzpf2dlnYME0A_7j1w-EVMd3I',
    appId: '1:1023790977092:web:69ede55a49b76c0784ec11',
    messagingSenderId: '1023790977092',
    projectId: 'psc-4fbce',
    authDomain: 'psc-4fbce.firebaseapp.com',
    storageBucket: 'psc-4fbce.appspot.com',
    measurementId: 'G-NEQ1W3FH9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsp1N1mGwdibd8egfhxgUSE2WnWiktlGQ',
    appId: '1:1023790977092:android:8f7f5733932fca2c84ec11',
    messagingSenderId: '1023790977092',
    projectId: 'psc-4fbce',
    storageBucket: 'psc-4fbce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxyWqzL9PdTyu0te6xXVlLFUnXjGsyIBw',
    appId: '1:1023790977092:ios:f844ba7e3edb169384ec11',
    messagingSenderId: '1023790977092',
    projectId: 'psc-4fbce',
    storageBucket: 'psc-4fbce.appspot.com',
    iosBundleId: 'com.example.psc',
  );

}